Fix issue labels (#165)
Regressed in c82ad0793843d80f691805a97ff5a603fad1ce54:

  Error: Unsupported attribute

    on locals.tf line 135, in locals:
   135:           ]) : lower("${item.repository}:${item.label}") => item

  This object does not have an attribute named "label".